### PR TITLE
[ML] Add state checkpoints during coarse parameter search for classification and regression

### LINKED ISSUE #1275: [ML] Persist/restore state during the coarse parameter search step of boosted tree training
Currently, we only persist state to allow us to restore from failure (or the user stopping the data frame analysis) after fine tuning of hyperparameter starts.

We could easily store sufficient information to be able to resume part way through coarse parameter search and I've seen this step cost up to 30% of our total training time.

### PR DESCRIPTION
**Pull request by tveasey**
Searching for initial parameters for boosted tree training is an expensive operation and it is possible to save state to allow this to resume with minimal loss of work. This PR adds checkpointing of sufficient state to resume after failure during this step. It also makes some tweaks to `CPersistUtils`. These include moving values into place where possible and adding some convenience functions to persist pointers.

The basic strategy is to introduce an initialisation stage variable to `CBoostedTreeImpl`. This tracks where initialisation reached at each checkpoint, so that it is possible to resume, skipping stages which have already been performed. It is necessary to additionally persist and restore some factory state.

Closes #1275.

### CODE REVIEW

File: include/core/CPersistUtils.h [hunk 1]
```diff
@@ -334,24 +334,48 @@ class CORE_EXPORT CPersistUtils {
         mutable std::string m_Token;
     };
 
-    //! Entry method for objects being restored
+    //! Restore \p collection reading state from \p inserter expecting \p tag for elements.
```
Comment (valeriy42) [inline include/core/CPersistUtils.h:337]:
```suggestion
    //! Restore \p collection reading state from \p traverser expecting \p tag for elements.
```

File: lib/maths/CBoostedTreeFactory.cc [hunk 2]
```diff
@@ -120,10 +135,22 @@ CBoostedTreeFactory::restoreFor(core::CDataFrame& frame, std::size_t dependentVa
...
+    switch (m_TreeImpl->m_InitializationStage) {
+    case CBoostedTreeImpl::E_FullyInitialized:
+        break;
+    case CBoostedTreeImpl::E_NotInitialized:
+    case CBoostedTreeImpl::E_SoftTreeDepthLimitInitialized:
+    case CBoostedTreeImpl::E_DepthPenaltyMultiplierInitialized:
+    case CBoostedTreeImpl::E_TreeSizePenaltyMultiplierInitialized:
+    case CBoostedTreeImpl::E_LeafWeightPenaltyMultiplierInitialized:
+    case CBoostedTreeImpl::E_DownsampleFactorInitialized:
+    case CBoostedTreeImpl::E_EtaInitialized:
```
Comment (valeriy42) [inline lib/maths/CBoostedTreeFactory.cc:147]: Are you actually setting all these stage values somewhere?

File: lib/maths/unittest/CBoostedTreeTest.cc [hunk 3]
```diff
@@ -1647,21 +1647,96 @@ BOOST_AUTO_TEST_CASE(testPersistRestore) {
...
+                               .numberFolds(2)
+                               .maximumNumberTrees(2)
+                               .maximumOptimisationRoundsPerHyperparameter(3)
+                               .trainingStateCallback(writeCheckpoint)
+                               .buildFor(*frame, cols - 1);
+        core::CJsonStatePersistInserter inserter(expectedState);
+        boostedTree->acceptPersistInserter(inserter);
+        expectedState.flush();
+    }
+
```
Comment (valeriy42) [inline lib/maths/unittest/CBoostedTreeTest.cc:1726]: Nice test overall, I think you need to check  that `checkpoints` contains the expected number of elements, otherwise mot may be empty and the loop below is useless.

Comment (tveasey) [reply lib/maths/unittest/CBoostedTreeTest.cc:1726]: Great point!

**Comment by tveasey** [comment]
Thanks @valeriy42 !

>  I've seen only Uninitialized and FullyInitialized. Did I miss it?

It happens in skipCheckpointIfAtOrAfter, i.e. at [this](https://github.com/elastic/ml-cpp/pull/1300/files#diff-192fe6f9f53bb6f2064155bc0f9c083aR1333) line.

File: lib/maths/CBoostedTreeFactory.cc (hunk 2 above)
Comment (tveasey) [reply lib/maths/CBoostedTreeFactory.cc:147]: As below, this happens in `skipCheckpointIfAtOrAfter`.

File: lib/maths/unittest/CBoostedTreeTest.cc (hunk 3 above)
Comment (tveasey) [reply lib/maths/unittest/CBoostedTreeTest.cc:1726]: See [ea2299c](https://github.com/elastic/ml-cpp/pull/1300/commits/ea2299cdcea8c00055b68725b31dc153580fafc2).

File: include/core/CPersistUtils.h (hunk 1 above)
Comment (tveasey) [reply include/core/CPersistUtils.h]: See [f6804a0](https://github.com/elastic/ml-cpp/pull/1300/commits/f6804a083088665fb4598869e321a17020d6277b).

File: lib/maths/unittest/CBoostedTreeTest.cc (hunk 3 above)
Comment (tveasey) [reply lib/maths/unittest/CBoostedTreeTest.cc:1726]: Note, I decided to just add a test that there is at least one checkpoint so we don't fail on changes to when we checkpoint.

**Comment by tveasey** [comment]
Thanks for the review @valeriy42! I've addressed all your comments. Could you take another look?

**Comment by tveasey** [comment]
retest

**Comment by tveasey** [comment]
Aarch64 CI seems to be unavailable at the moment. I'm going to go ahead and merge this anyway, since it already passed in an earlier version, and this is still unsupported.
