### PR TITLE
[ML] Add unit test checks for new hyperparameters in supervised learning

### LINKED ISSUE #849: [ML] Trees can have leaves without any data points
It seams that the splitting algorithm continues to split a node even if there are no data points in one of the branches. This leads to creation of degenerated large trees, which are only limited by the maximum tree size. This also breaks algorithms like TreeSHAP, which assume that every leaf contains some data.

### LINKED ISSUE #851: [ML] Add unit test checks for new hyperparameters in supervised learning
For the tests with all hyperparameters set (e.g. `m_RegularizationOverride.*`), we need to check that those would set the actual hyperparameter values (e.g. `m_Regularization.*`). I just noticed that setting `softTreeDepthLimit` and `softTreeDepthTolerance` was missing and the unit test  `testRunBoostedTreeRegressionTrainingWithParams` didn't fail.

### PR DESCRIPTION
**Pull request by valeriy42**
This PR adds check that user-specified hyperparameters are used as final hyperparameters by the boosted trees. Implementation of the unit test required factoring out classes `CBoostedTreeHyperparameters` and `CBoostedTreeRegularization` from `CBoostedTreeImpl`.

Also I added the setting of some user-specified hyperparameters in `CBoostedTreeFactory.cc` that were missing before.

Fixes #851 
Fixes #849

### CODE REVIEW

File: include/maths/CBoostedTreeHyperparameters.h [hunk 1]
```diff
@@ -0,0 +1,242 @@
...
+    "regularization_leaf_weight_penalty_multiplier"};
+template<typename T>
+const std::string CBoostedTreeRegularization<T>::REGULARIZATION_SOFT_TREE_DEPTH_LIMIT_TAG{
+    "regularization_soft_tree_depth_limit"};
+template<typename T>
+const std::string CBoostedTreeRegularization<T>::REGULARIZATION_SOFT_TREE_DEPTH_TOLERANCE_TAG{
+    "regularization_soft_tree_depth_tolerance"};
+
+//! \brief The algorithm parameters we'll directly optimise to improve test error.
+class CBoostedTreeHyperparameters {
```
Comment (tveasey) [inline include/maths/CBoostedTreeHyperparameters.h]: I don't think Windows will like this:
```suggestion
class MATHS_EXPORT CBoostedTreeHyperparameters {
```

File: include/maths/CBoostedTreeImpl.h [hunk 2]
```diff
@@ -120,11 +123,13 @@ class MATHS_EXPORT CBoostedTreeImpl final {
     //! Visit this tree trainer implementation.
     void accept(CBoostedTree::CVisitor& visitor);
 
+    //! \return Class containing best hyperparameters.
```
Comment (tveasey) [inline include/maths/CBoostedTreeImpl.h]: nit: strictly this is an object of the class but how about
```suggestion
    //! \return The best hyperparameters for validation error found so far.
```
